/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'lawn' : IDL.Null,
  'suit' : IDL.Null,
  'shawl' : IDL.Null,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
  'discountedPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([IDL.Opt(Category)], [IDL.Vec(Product)], ['query']),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'lawn' : IDL.Null,
    'suit' : IDL.Null,
    'shawl' : IDL.Null,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
    'discountedPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func(
        [IDL.Opt(Category)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };